---
- name: Ensure Azure Resource Group exists
  hosts: localhost
  gather_facts: no

  tasks:
  
    - name: Ensure resource group is present
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: westus2
        state: present
     
