---
- name: Ensure Azure Resource Group exists
  hosts: localhost
  gather_facts: no
  vars:
    user_action: "{{ user_action }}"
  tasks:
    - name: Debug user_action variable
      debug:
        msg: "The user_action variable is set to: {{ user_action }}"

    - name: Test simple condition
      debug:
        msg: "This is a test message for create action."
      when: user_action == 'Create'

    - name: Ensure Azure CLI is installed
      apt:
        name: azure-cli
        state: present

    - name: Log in to Azure CLI
      shell: az login --service-principal -u "{{ azure_client_id }}" -p "{{ azure_client_secret }}" --tenant "{{ azure_tenant_id }}"
      register: login_result
      no_log: true
      when: user_action == 'Create'

    - name: Set Azure subscription
      shell: az account set --subscription "{{ azure_subscription_id }}"
      no_log: true
      when: user_action == 'Create'

    - name: Ensure resource group is present
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: westus2
        state: present
      when: user_action == 'Create'
