---
- name: Ensure Azure Resource Group Exists
  hosts: localhost
  tasks:
    - name: Ensure resource group
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: westus2
      register: rg
    - debug:
        msg: "Resource Group {{ rg.state }} in {{ rg.location }}"
