---
- name: Ensure Azure Container Registry exists
  hosts: localhost
  gather_facts: no
  collections:
    - azure.azcollection
  tasks:
    - name: Ensure ACR is present
      azure.azcollection.azure_rm_containerregistry:
        resource_group: myResourceGroup
        name: myACR
        sku: Basic
        admin_user_enabled: true
        location: westus2
        state: present
      when: user_action == "Create"
