---
- name: Ensure Azure Resource Group exists
  hosts: localhost
  gather_facts: no
  vars:
    user_action: "{{ user_action }}"
  tasks:
    - name: Gather OS family fact
      setup:
        filter: ansible_os_family
      when: user_action == 'Create'

    - name: Debug user_action variable
      debug:
        msg: "The user_action variable is set to: {{ user_action }}"

    - name: Ensure Azure CLI is installed
      become: yes
      yum:
        name: azure-cli
        state: present
      when: ansible_os_family == "RedHat" and user_action == 'Create'

    - name: Ensure resource group is present
      azure_rm_resourcegroup:
        name: myResourceGroup
        location: westus2
        state: present
      when: user_action == 'Create'
