---
- name: Ensure Azure Container Instance is running
  hosts: localhost
  tasks:
    - name: Ensure ACI is present
      azure_rm_containerinstance:
        resource_group: myResourceGroup
        name: myACI
        image: myacr.azurecr.io/aci-helloworld:latest
        location: westus2
        os_type: Linux
        cpu_cores: 1
        memory_in_gb: 1.5
        ports:
          - port: 80
            protocol: TCP
        state: present
