---
- name: Ensure Azure Container Instance is running
  hosts: localhost
  gather_facts: no
  collections:
    - azure.azcollection
  tasks:
    - name: Ensure ACI is present
      azure.azcollection.azure_rm_containerinstance:
        resource_group: myResourceGroup
        name: myACI
        os_type: linux
        ip_address: public
        location: westus2
        containers:
          - name: mycontainer1
            image: mcr.microsoft.com/azuredocs/aci-helloworld:latest
            memory: 1.5
            ports:
              - 80
        state: present
      register: aci_result
      when: user_action == "Create"

    - name: Fetch ACI details
      azure.azcollection.azure_rm_containerinstance_info:
        resource_group: myResourceGroup
        name: myACI
      register: aci_info
      when: user_action == "Create"

    - name: Print ACI URL
      debug:
        msg: "ACI URL: http://{{ aci_info.ansible_facts.azure_containerinstances[0].ip_address }}"
      when: user_action == "Create"
