---
- name: Ensure Azure Container Instance is running
  hosts: localhost
  gather_facts: no
  vars:
    user_action: "{{ user_action }}"
  tasks:
    - name: Debug user_action variable
      debug:
        msg: "The user_action variable is set to: {{ user_action }}"

    - name: Ensure Azure CLI is installed
      apt:
        name: azure-cli
        state: present
      when: ansible_os_family == "Debian"

    - name: Log in to Azure CLI
      shell: az login --service-principal -u "{{ azure_client_id }}" -p "{{ azure_client_secret }}" --tenant "{{ azure_tenant_id }}"
      register: login_result
      no_log: true
      when: user_action == 'Create'

    - name: Set Azure subscription
      shell: az account set --subscription "{{ azure_subscription_id }}"
      no_log: true
      when: user_action == 'Create'

    - name: Ensure ACI is present
      azure_rm_containerinstance:
        resource_group: myResourceGroup
        name: myACI
        image: myacr.azurecr.io/aci-helloworld:latest
        location: westus2
        os_type: Linux
        cpu_cores: 1
        memory_in_gb: 1.5
        ports:
          - port: 80
            protocol: TCP
        state: present
      register: aci
      when: user_action == "Create"

    - name: Get ACI details
      azure_rm_containerinstance_info:
        resource_group: myResourceGroup
        name: myACI
      register: aci_info
      when: user_action == "Create"

    - name: Print ACI URL
      debug:
        msg: "ACI URL: http://{{ aci_info.ansible_facts.azure_containerinstances[0].ip_address }}:80"
      when: user_action == "Create"
