---
- name: Destroy Azure Resource Group and its contents
  hosts: localhost
  gather_facts: no
  collections:
    - azure.azcollection
  tasks:
    - name: Ensure resource group is absent
      azure.azcollection.azure_rm_resourcegroup:
        name: myResourceGroup
        state: absent
      when: user_action == "Destroy"
