---
- name: Destroy Azure Resource Group and its contents
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Ensure resource group is absent
      azure_rm_resourcegroup:
        name: myResourceGroup
        state: absent
      when: action == "Destroy"
