---
- name: Create and deploy Azure Function App
  hosts: localhost
  vars:
    resource_group: "myResourceGroup"
    location: "East US"
    function_app_name: "myFunctionAppDemo"
    storage_account_name: "mystorageaccountdemo"
    app_service_plan: "myAppServicePlanDemo"
    function_code_path: "../function_code"
  tasks:

    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create a storage account
      azure.azcollection.azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ storage_account_name }}"
        sku: "Standard_LRS"
        kind: "StorageV2"
        location: "{{ location }}"

    - name: Create a Consumption Plan
      azure.azcollection.azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ app_service_plan }}"
        sku:
          tier: "Dynamic"
          size: "Y1"
        is_linux: false

    - name: Create a Function App
      azure.azcollection.azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        plan: "{{ app_service_plan }}"
        storage_account_name: "{{ storage_account_name }}"
        os_type: "Windows"
        https_only: true

    - name: Prepare function code for deployment
      synchronize:
        src: "{{ function_code_path }}/"
        dest: "/tmp/function_code/"
        mode: pull
        delete: no

    - name: Zip the function code
      archive:
        path: "/tmp/function_code/"
        dest: "/tmp/function_code.zip"
        format: zip

    - name: Deploy the function code to Azure
      azure.azcollection.azure_rm_functionappdeployment:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        src: "/tmp/function_code.zip"

    - name: Restart the Azure Function App
      azure.azcollection.azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        state: restarted

    - name: Return the function URL
      debug:
        msg: "Your function URL is: https://{{ function_app_name }}.azurewebsites.net/api/hello"
