---
- name: Create and deploy Azure Function App on Linux Consumption Plan
  hosts: localhost
  gather_facts: no
  collections:
    - azure.azcollection
  vars:
    resource_group: "myResourceGroup"
    location: "East US"
    function_app_name: "myLinuxFunctionAppDemo"
    storage_account_name: "mystoragedemolinux"
    app_service_plan: "myLinuxAppServicePlanDemo"
    function_code_path: "../function_code"
    zip_file_path: "/tmp/function_code.zip"
    container_name: "functionappcode"
    blob_name: "function_code.zip"
  tasks:

    - name: Ensure the resource group exists
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
        state: present

    - name: Ensure the storage account exists
      azure.azcollection.azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ storage_account_name }}"
        sku: "Standard_LRS"
        kind: "StorageV2"
        location: "{{ location }}"
        state: present

    - name: Ensure the Blob Storage container exists
      azure.azcollection.azure_rm_storageblob:
        resource_group: "{{ resource_group }}"
        account_name: "{{ storage_account_name }}"
        container_name: "{{ container_name }}"
        public_access: "blob"
        state: "present"

    - name: Zip the function code using shell command
      ansible.builtin.command:
        cmd: "zip -r {{ zip_file_path }} ."
        chdir: "{{ function_code_path }}"
      args:
        creates: "{{ zip_file_path }}"

    - name: Ensure the function code is uploaded to Blob Storage
      azure.azcollection.azure_rm_storageblob:
        resource_group: "{{ resource_group }}"
        account_name: "{{ storage_account_name }}"
        container_name: "{{ container_name }}"
        name: "{{ blob_name }}"
        src: "{{ zip_file_path }}"
        type: "block"
        state: present

    - name: Ensure the Linux Consumption Plan exists
      azure.azcollection.azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ app_service_plan }}"
        sku:
          tier: "Dynamic"
          size: "Y1"
        is_linux: true
        state: present

    - name: Ensure the Function App exists
      azure.azcollection.azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        plan: "{{ app_service_plan }}"
        storage_account_name: "{{ storage_account_name }}"
        os_type: "Linux"
        runtime: "python|3.9"
        https_only: true
        app_settings:
          - name: "WEBSITE_RUN_FROM_PACKAGE"
            value: "https://{{ storage_account_name }}.blob.core.windows.net/{{ container_name }}/{{ blob_name }}"
        state: present

    - name: Restart the Azure Function App if necessary
      azure.azcollection.azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        state: restarted

    - name: Return the function URL
      debug:
        msg: "Your function URL is: https://{{ function_app_name }}.azurewebsites.net/api/hello"
