---
- name: Create and deploy Azure Function App on Linux Consumption Plan
  hosts: localhost
  gather_facts: no
  collections:
    - azure.azcollection
  vars:
    resource_group: "myResourceGroup"
    location: "East US"
    function_app_name: "myLinuxFunctionAppDemo"
    storage_account_name: "mystoragedemolinux"
    app_service_plan: "myLinuxAppServicePlanDemo"
    function_code_path: "../function_code"
    zip_file_path: "/tmp/function_code.zip"
  tasks:

    - name: Create a resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create a storage account
      azure.azcollection.azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ storage_account_name }}"
        sku: "Standard_LRS"
        kind: "StorageV2"
        location: "{{ location }}"

    - name: Create a Linux Consumption Plan
      azure.azcollection.azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ app_service_plan }}"
        sku:
          tier: "Dynamic"
          size: "Y1"
        is_linux: true

    - name: Create a Function App on Linux
      azure.azcollection.azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        plan: "{{ app_service_plan }}"
        storage_account_name: "{{ storage_account_name }}"
        os_type: "Linux"
        runtime: "python|3.9"
        https_only: true

    - name: Zip the function code using shell command
      ansible.builtin.command:
        cmd: "zip -r {{ zip_file_path }} ."
        chdir: "{{ function_code_path }}"

    - name: Deploy the function code using Azure CLI
      ansible.builtin.command:
        cmd: "az functionapp deployment source config-zip -g {{ resource_group }} -n {{ function_app_name }} --src {{ zip_file_path }}"

    - name: Restart the Azure Function App
      azure.azcollection.azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        state: restarted

    - name: Return the function URL
      debug:
        msg: "Your function URL is: https://{{ function_app_name }}.azurewebsites.net/api/hello"
