---
- name: Destroy Azure resources created for the demo
  hosts: localhost
  gather_facts: no
  collections:
    - azure.azcollection
  vars:
    resource_group: "myResourceGroup"
    function_app_name: "myLinuxFunctionAppDemo"
    app_service_plan: "myLinuxAppServicePlanDemo"
    storage_account_name: "mystoragedemolinux"
    container_name: "functionappcode"
    blob_name: "function_code.zip"
  tasks:

    - name: Ensure the Function App is absent
      azure.azcollection.azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        state: absent

    - name: Ensure the App Service Plan is absent
      azure.azcollection.azure_rm_appserviceplan:
        resource_group: "{{ resource_group }}"
        name: "{{ app_service_plan }}"
        state: absent

    - name: Ensure the Blob is deleted from Storage
      azure.azcollection.azure_rm_storageblob:
        resource_group: "{{ resource_group }}"
        account_name: "{{ storage_account_name }}"
        container_name: "{{ container_name }}"
        name: "{{ blob_name }}"
        state: absent

    - name: Ensure the Storage Account is absent
      azure.azcollection.azure_rm_storageaccount:
        resource_group: "{{ resource_group }}"
        name: "{{ storage_account_name }}"
        state: absent

    - name: Ensure the resource group is absent
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        state: absent

    - name: Confirm deletion
      debug:
        msg: "Resource group '{{ resource_group }}' and all associated resources have been deleted."
